import os, subprocess
from pathlib import Path
import string, random
import typer

# undo specific imports
from undo.commands.secret import secret_misc
from undo.utils import const, secret_utils


def encrypt_secret(secret, secret_path, *, overwrite=False):
    # while upsert will do the check exists logic
    # we can't give good enough errors if we use it, so...
    if overwrite is False: check_secret_exists(secret_path, overwrite)

    # use the standard upsert to encrypt
    # it'll prompt if secret is None, upsert will prompt
    # if overwrite is false, it'll skip changing the secret
    upsert_secret = secret_utils.upsert_secret(secret_path, secret)

    # if secret was set/generated but it wasn't updated, it'll be because one existed
    if secret and secret != upsert_secret and not overwrite:
        masked_secret = secret_utils.mask_secret(secret)
        echo = f"A secret already exists at '{secret_path}'\n" \
               f"so it was not changed to '{masked_secret}'.\n\n" \
               f"To overwrite the existing secret, include the -o/--override flag " \
               f"in your commmand."
        typer.secho("\nNo change made", fg=const.INFO_TEXT_COLOUR)
        typer.secho(echo)

    # otherwise, be it set, generated or prompted for, it should've been set
    else:
        masked_secret = secret_utils.mask_secret(upsert_secret)
        echo = f"The secret '{masked_secret}' has been encrypted\n" \
               f"and stored at the location '{secret_path}'"
        typer.secho("\nEncryptio!", fg=const.SCSS_TEXT_COLOUR)
        typer.secho(echo)

    return secret_path


def check_autogenerate(secret, *, secret_length=30):
    # if secret explicitly is true, autogenerate
    if secret is True:
        secret = secret_misc.generate_secret(chars=secret_length, include_symbols=True)
        typer.secho("\nA secret has been autogenerated..", fg=const.INFO_TEXT_COLOUR)
        typer.secho(f"\t{secret_utils.mask_secret(secret)}")

    # if secret explicitly is false, set to none so it's prompted for by secret_upsert
    elif secret is False:
        secret = None

    return secret


def check_secret_exists(secret_path, overwrite):
    secret_check = Path(secret_path).exists()

    if secret_check and not overwrite:
        typer.secho("\nHmm?", fg=const.ERRR_TEXT_COLOUR)
        typer.secho(f"A secret already exists at '{secret_path}',")
        typer.secho("either delete it or set the --overwrite (-o) flag.")
        raise typer.Exit(1)

    return secret_check